/* FactoryPatient.java
Patient factory for JPA entity
Author : Bruneez Apollis(222127600)
Date: March 2025
*/
package za.ac.cput.factory;

import za.ac.cput.domain.Patient;

public class FactoryPatient {

    /**
     * Create a Patient entity. ID is generated by JPA.
     *
     * @param fullName required
     * @param email    required (basic format check)
     * @param phone    optional (can be null/blank)
     */
    public static Patient createPatient(String fullName, String email, String phone) {
        if (isBlank(fullName)) throw new IllegalArgumentException("Full name is required");
        if (isBlank(email))    throw new IllegalArgumentException("Email is required");
        if (!email.contains("@")) throw new IllegalArgumentException("Email looks invalid");

        String safePhone = isBlank(phone) ? null : phone.trim();
        return new Patient(fullName.trim(), email.trim(), safePhone);
    }

    private static boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }
}
