/* FactoryDoctor.java
Doctor factory for JPA entity
Author : Matthew Michael Engelbrecht(222381086)
Date : March 2025
*/
package za.ac.cput.factory;

import za.ac.cput.domain.Doctor;

import java.util.Objects;

public class FactoryDoctor {

    /**
     * Create a Doctor entity. ID is generated by JPA.
     *
     * @param fullName   Doctor's full name (required)
     * @param speciality e.g. "GP", "Dentist" (required)
     * @param clinicCity e.g. "Cape Town" (required)
     */
    public static Doctor createDoctor(String fullName, String speciality, String clinicCity) {
        if (isBlank(fullName))   throw new IllegalArgumentException("Full name is required");
        if (isBlank(speciality)) throw new IllegalArgumentException("Speciality is required");
        if (isBlank(clinicCity)) throw new IllegalArgumentException("Clinic city is required");

        // JPA constructor; ID is generated with @GeneratedValue(strategy = UUID)
        return new Doctor(fullName.trim(), speciality.trim(), clinicCity.trim());
    }

    private static boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }
}
